# Generated by Django 4.2.30 on 2026-05-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0002_customer_order_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='optical.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal note for staff only'),
        ),
        migrations.AddField(
            model_name='order',
            name='frame_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='lens_coating',
            field=models.CharField(blank=True, help_text='e.g. Anti-Reflection, Photochromic, UV400', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='lens_type',
            field=models.CharField(blank=True, help_text='e.g. Single Vision, Bifocal, Progressive, Blue Cut', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('eyeglasses', 'Eyeglasses'), ('sunglasses', 'Sunglasses'), ('contact_lenses', 'Contact Lenses'), ('frames', 'Frames'), ('reading_glasses', 'Reading Glasses'), ('accessories', 'Accessories')], max_length=50),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('right_sph', models.CharField(blank=True, max_length=10, verbose_name='Right SPH')),
                ('right_cyl', models.CharField(blank=True, max_length=10, verbose_name='Right CYL')),
                ('right_axis', models.CharField(blank=True, max_length=10, verbose_name='Right Axis')),
                ('right_add', models.CharField(blank=True, max_length=10, verbose_name='Right ADD (near)')),
                ('right_va', models.CharField(blank=True, max_length=10, verbose_name='Right VA')),
                ('left_sph', models.CharField(blank=True, max_length=10, verbose_name='Left SPH')),
                ('left_cyl', models.CharField(blank=True, max_length=10, verbose_name='Left CYL')),
                ('left_axis', models.CharField(blank=True, max_length=10, verbose_name='Left Axis')),
                ('left_add', models.CharField(blank=True, max_length=10, verbose_name='Left ADD (near)')),
                ('left_va', models.CharField(blank=True, max_length=10, verbose_name='Left VA')),
                ('pd', models.CharField(blank=True, max_length=20, verbose_name='PD (Pupillary Distance)')),
                ('notes', models.TextField(blank=True, verbose_name='Doctor Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='optical.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='optical.customer')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_id_str', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='optical.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optical.product')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-added_at'],
                'unique_together': {('customer', 'product_id_str')},
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], default=5)),
                ('review', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before showing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='optical.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='optical.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'customer')},
            },
        ),
    ]
